/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.Conn;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lovanto
 */
public class Dashboard extends javax.swing.JFrame {
    //Init var
    public Conn conn;

    /**
     * When menu logout clicked or not login yet, make some menu cannot 
     * be access until they login again.
    */
    private void setMenuLogout() {
        menuLogin.setEnabled(true);
        menuExit.setEnabled(true);
        menuTransaksi.setEnabled(false);
        menuJasa.setEnabled(false);
        menuLogout.setEnabled(false);
        menuPengguna.setEnabled(false);
    }
    
    /**
     * When menu user success login, make some menu can be access 
     * until they logout or program closed.
    */
    private void setMenuLogin() {
        menuLogin.setEnabled(false);
        menuExit.setEnabled(true);
        menuTransaksi.setEnabled(true);
        menuJasa.setEnabled(true);
        menuLogout.setEnabled(true);
        menuPengguna.setEnabled(true);
    }
    
    /**
     * This method is used for check user already registered or have a valid
     * account in our database.
     * @return true if username and password valid.
     */
    public boolean cekLogin(){
        String namaPengguna = "";
        try{
            String sql="SELECT * FROM pengguna WHERE username='"
                    +textUsername.getText()+
                    "' and kataSandi ='"+textPassword.getText()+"'";
            ResultSet rs = conn.getData(sql);
            while (rs.next()){
                namaPengguna = rs.getString(1);
            }
            if(namaPengguna.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Login Gagal!");    
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Anda Berhasil Login!"
                +"\nSelamat Datang " + namaPengguna);
                setMenuLogin();
                dialogLogin.setVisible(false);
                return true;
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Kesalahan: " + e);
         }
        return false;
    }
     
    public Dashboard() {
        initComponents();
        setMenuLogout();
        conn = new Conn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogLogin = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        textPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAuth = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuMenu = new javax.swing.JMenu();
        menuPengguna = new javax.swing.JMenuItem();
        menuJasa = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();

        dialogLogin.setTitle("Login | Flash Laundry");
        dialogLogin.setMinimumSize(new java.awt.Dimension(400, 462));
        dialogLogin.setResizable(false);
        dialogLogin.setSize(new java.awt.Dimension(400, 462));
        dialogLogin.getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Lato", 1, 30)); // NOI18N
        jLabel3.setText("Login");
        dialogLogin.getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 50, 80, 39);

        jLabel4.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel4.setText("Username");
        dialogLogin.getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 120, 64, 19);

        jLabel5.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        dialogLogin.getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 190, 61, 19);

        textUsername.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        textUsername.setText("lovanto");
        dialogLogin.getContentPane().add(textUsername);
        textUsername.setBounds(70, 150, 270, 30);

        btnBatal.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        btnBatal.setText("Batal");
        dialogLogin.getContentPane().add(btnBatal);
        btnBatal.setBounds(270, 290, 67, 27);

        btnLogin.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        dialogLogin.getContentPane().add(btnLogin);
        btnLogin.setBounds(70, 290, 160, 27);

        textPassword.setText("Inzanami123");
        dialogLogin.getContentPane().add(textPassword);
        textPassword.setBounds(70, 220, 270, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flash Laundry Apps");
        setBackground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(556, 222));
        setResizable(false);
        setSize(new java.awt.Dimension(546, 252));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 190, 0, 0);

        jLabel1.setText("Selamat Datang di Flash Laundry...");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 180, 240, 14);

        menuAuth.setText("Auth");

        menuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        menuAuth.add(menuLogin);

        menuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuAuth.add(menuLogout);

        jMenuBar1.add(menuAuth);

        menuMenu.setText("Menu");

        menuPengguna.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuPengguna.setText("User");
        menuPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenggunaActionPerformed(evt);
            }
        });
        menuMenu.add(menuPengguna);

        menuJasa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menuJasa.setText("Jasa");
        menuJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJasaActionPerformed(evt);
            }
        });
        menuMenu.add(menuJasa);

        menuTransaksi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuTransaksi.setText("Transaksi");
        menuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiActionPerformed(evt);
            }
        });
        menuMenu.add(menuTransaksi);

        jMenuBar1.add(menuMenu);

        menuExit.setText("Exit");
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When menu login clicked do:
     * set text field null, then show dialog login.
    */
    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
//        textUsername.setText("");
//        textPassword.setText("");
        dialogLogin.setVisible(true);
    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog (null, "Yakin ingin logout?");
        if(dialogResult == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Anda berhasil logout");
            setMenuLogout();
        }
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenggunaActionPerformed
        new Registrasi().show();
    }//GEN-LAST:event_menuPenggunaActionPerformed

    private void menuJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJasaActionPerformed
        new InputJasa().show();
    }//GEN-LAST:event_menuJasaActionPerformed

    private void menuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiActionPerformed
        new InputTransaksi().show();
    }//GEN-LAST:event_menuTransaksiActionPerformed

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuExitMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        boolean loginCheck = cekLogin();
        if(loginCheck == true) dialogLogin.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnLogin;
    private javax.swing.JDialog dialogLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAuth;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenuItem menuJasa;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuItem menuPengguna;
    private javax.swing.JMenuItem menuTransaksi;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
