/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.Conn;
import Models.Pengguna;
import Controller.ControllerPengguna;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lovanto
 */
public class Registrasi extends javax.swing.JFrame {
    //Init var
    private Object tabel;
    private ControllerPengguna tabelDataPengguna;
    private Conn conn;
    /**
     * Creates new form Registrasi
     */
    public Registrasi() {
        initComponents();
        conn = new Conn();
        tabelDataPengguna = new ControllerPengguna();
        tablePengguna.setModel(tabelDataPengguna);
        tampilData();
        SetEditOff();
    }
    
    private void tampilData(){
        try{
            int baris = tablePengguna.getRowCount();
            for(int i = 0; i < baris; i++) {
                tabelDataPengguna.delete(0, baris);
            }
            String sql = "SELECT * FROM pengguna";
            ResultSet rs = conn.getData(sql);
            while(rs.next()){
                Pengguna pengguna = new Pengguna();
                pengguna.setUsername(rs.getString(1));
                pengguna.setNoHP(rs.getString(2));
                pengguna.setAlamatPengguna(rs.getString(3));
                pengguna.setEmail(rs.getString(4));
                pengguna.setKataSandi(rs.getString(5));
                tabelDataPengguna.add(pengguna);
            }
        } catch (SQLException ex) {
            System.err.print(ex);
        }
    }
    
    public void TampilText(){
        int row = 0;
        row = tablePengguna.getSelectedRow();
        Pengguna pengguna = tabelDataPengguna.get(row);
        textUsername.setText(pengguna.getUsername());
        textHP.setText(pengguna.getNoHP());
        textAlamat.setText(pengguna.getAlamatPengguna());
        textEmail.setText(pengguna.getEmail());
        textPassword.setText(pengguna.getKataSandi());
        btnSave.setEnabled(false);
        btnNew.setEnabled(false);
        SetEditOn();
    }
    
    public void clearText(){
        textUsername.setText("");
        textHP.setText("");
        textAlamat.setText("");
        textEmail.setText("");
        textPassword.setText("");
    }
    
    public void SetEditOff(){
        textUsername.setEnabled(false);
        textHP.setEnabled(false);
        textAlamat.setEnabled(false);
        textEmail.setEnabled(false);
        textPassword.setEnabled(false);
        btnCancel.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnNew.setEnabled(true);
    }
    
    public void SetEditOn(){
        textUsername.setEnabled(true);
        textHP.setEnabled(true);
        textAlamat.setEnabled(true);
        textEmail.setEnabled(true);
        textPassword.setEnabled(true);
        btnCancel.setEnabled(false);
        btnDelete.setEnabled(true);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnNew.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrasi = new java.awt.Label();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePengguna = new javax.swing.JTable();
        textUsername = new javax.swing.JTextField();
        textHP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAlamat = new javax.swing.JTextArea();
        textEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        textPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1149, 590));
        setResizable(false);
        setSize(new java.awt.Dimension(1149, 590));
        getContentPane().setLayout(null);

        Registrasi.setAlignment(java.awt.Label.CENTER);
        Registrasi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registrasi.setText("Registrasi");
        getContentPane().add(Registrasi);
        Registrasi.setBounds(120, 20, 116, 36);

        label1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label1.setText("No. HP");
        getContentPane().add(label1);
        label1.setBounds(30, 140, 290, 24);

        label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label2.setText("Username");
        getContentPane().add(label2);
        label2.setBounds(30, 80, 290, 24);

        label3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label3.setText("Alamat");
        getContentPane().add(label3);
        label3.setBounds(30, 200, 290, 24);

        label4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label4.setText("Email");
        getContentPane().add(label4);
        label4.setBounds(30, 340, 290, 24);

        label5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label5.setText("Kata Sandi");
        getContentPane().add(label5);
        label5.setBounds(30, 400, 290, 24);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(97, 34, 0, 0);

        tablePengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePengguna);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(360, 30, 760, 500);
        getContentPane().add(textUsername);
        textUsername.setBounds(30, 110, 290, 20);
        getContentPane().add(textHP);
        textHP.setBounds(30, 170, 290, 20);

        textAlamat.setColumns(20);
        textAlamat.setRows(5);
        jScrollPane2.setViewportView(textAlamat);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 230, 290, 96);
        getContentPane().add(textEmail);
        textEmail.setBounds(30, 370, 290, 20);

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        btnSave.setText("Save");
        btnSave.setPreferredSize(new java.awt.Dimension(73, 23));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(140, 470, 73, 23);

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(73, 23));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(250, 470, 73, 23);

        btnNew.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        btnNew.setText("New");
        btnNew.setPreferredSize(new java.awt.Dimension(73, 23));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew);
        btnNew.setBounds(30, 470, 73, 23);

        btnDelete.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(73, 23));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(140, 510, 73, 23);

        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(73, 23));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(250, 510, 73, 23);
        getContentPane().add(textPassword);
        textPassword.setBounds(30, 430, 290, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String username = textUsername.getText();
        String nohp = textHP.getText();
        String alamat = textAlamat.getText();
        String email = textEmail.getText();
        String password = textPassword.getText();
        if ((username.isEmpty()) | (nohp.isEmpty()) | (alamat.isEmpty()) 
                | (email.isEmpty()) | (password.isEmpty())){
            JOptionPane.showMessageDialog(null, "data tidak boleh kosong, " +
                "silahkan dilengkapi");
            textUsername.requestFocus();
        }else {
            try {
                String sql = "INSERT INTO `pengguna` (`username`, `noHP`, "
                        + "`alamatPengguna`, `email`, `kataSandi`, `create_date`) "
                        + "VALUES ("
                        + "'" + username + "',"
                        + "'" + nohp + "',"
                        + "'" + alamat + "',"
                        + "'" + email + "',"
                        + "'" + password + "',"
                        + null 
                + ")";
                conn.query(sql);
                tampilData();
                JOptionPane.showMessageDialog(null, username + " Berhasil Disimpan");
                clearText();
                SetEditOff();
                btnNew.setEnabled(true);
            }catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearText();
        textUsername.requestFocus();
        SetEditOn();
        btnSave.setEnabled(true);
        btnDelete.setEnabled(false);
        btnNew.setEnabled(false);
        btnCancel.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearText();
        SetEditOff();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tablePenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenggunaMouseClicked
        if(evt.getClickCount()==1){
            TampilText();
        }
        btnCancel.setEnabled(true);
        btnNew.setEnabled(false);
        textUsername.setEnabled(false);
    }//GEN-LAST:event_tablePenggunaMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String username = textUsername.getText();
        int app;
        if ((app = JOptionPane.showConfirmDialog(null, "Anda yakin akan menghapus data "
                + username+ " ?", "Perhatian", JOptionPane.YES_NO_OPTION)) == 0){
            try {
                String sql = "DELETE FROM pengguna WHERE"
                + " username = '" + username+ "'";
                conn.query(sql);
                tampilData();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                clearText();
                SetEditOff();
                btnNew.setEnabled(true);
            }catch (Exception ex) {
                System.err.print(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String username = textUsername.getText();
        String nohp = textHP.getText();
        String alamat = textAlamat.getText();
        String email = textEmail.getText();
        String password = textPassword.getText();
        if ((username.isEmpty()) | (nohp.isEmpty()) | (alamat.isEmpty()) 
                | (email.isEmpty()) | (password.isEmpty())){
            JOptionPane.showMessageDialog(null, "data tidak boleh kosong, " +
                "silahkan dilengkapi");
            textUsername.requestFocus();
        }else {
            try {
                String sql = "UPDATE `pengguna` SET "
                        + "noHP = '" + nohp + "',"
                        + "alamatPengguna = '" + alamat + "',"
                        + "email = '" + email + "',"
                        + "kataSandi = '" + password + "' WHERE "
                        + "username = '" + username + "'";
                conn.query(sql);
                tampilData();
                JOptionPane.showMessageDialog(null, username + " Berhasil Diperbarui");
                clearText();
                SetEditOff();
                btnNew.setEnabled(true);
            }catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Registrasi;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JTable tablePengguna;
    private javax.swing.JTextArea textAlamat;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textHP;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
